image: node:14.19.3

stages:
  - deploy

deploy:
  stage: deploy
  script:
    - echo "//gitlab.noosoft.ru/api/v4/projects/4/packages/npm/:_authToken=${CI_JOB_TOKEN}">.npmrc
    - export CI_JOB_TOKEN=XDqzYa3QzsosjGBjy-Wk npm publish